# Generated by Django 3.2 on 2021-04-11 04:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('region', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
                ('address', models.TextField()),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/hospital/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_type')),
            ],
        ),
    ]
