# Generated by Django 3.2 on 2021-04-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210411_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients Info'},
        ),
    ]
