# Generated by Django 3.2 on 2021-04-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurancecompany', '0001_initial'),
        ('hospital', '0001_initial'),
        ('patient', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_status_code', models.CharField(max_length=8)),
                ('status_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_number', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('update_date', models.DateField()),
                ('claim_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.claimstatus')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('insurance_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancecompany.company')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
